import pandas as pd
import os

def read_imu_csv(file_path):
    """
    Reads IMU data from a specified CSV file.

    Args:
        file_path (str): The absolute path to the IMU data CSV file.
                         Assumes columns like 'timestamp', 'accel_x', 'accel_y', 'accel_z',
                         'gyro_x', 'gyro_y', 'gyro_z', 'mag_x', 'mag_y', 'mag_z'.

    Returns:
        pd.DataFrame: A DataFrame containing the IMU data, or None if the file is not found or an error occurs.
    """
    if not os.path.exists(file_path):
        print(f"Error: IMU data file not found at {file_path}")
        return None

    try:
        with open(file_path, 'r') as f:
            header_line = f.readline().strip()
        
        # Read the CSV data, using the first line as header
        df_imu = pd.read_csv(file_path, header=0)
        # Remove '#' from column names if present
        df_imu.columns = df_imu.columns.str.lstrip('# ').str.strip()
        
        # Rename 'Time (seconds)' column to 'timestamp' for consistency
        if 'Time (seconds)' in df_imu.columns:
            df_imu.rename(columns={'Time (seconds)': 'timestamp'}, inplace=True)
        
        # Convert all column names to lowercase
        df_imu.columns = df_imu.columns.str.lower()
        print(f"Successfully loaded IMU data from {file_path}.")
        print(f"IMU DataFrame shape: {df_imu.shape}")
        return df_imu
    except Exception as e:
        print(f"Error reading IMU data from {file_path}: {e}")
        return None



def read_imu_data(file_path):
    """
    Reads IMU data from a specified file, dispatching based on file extension.

    Args:
        file_path (str): The absolute path to the IMU data file (e.g., .csv or .data).

    Returns:
        pd.DataFrame: A DataFrame containing the IMU data, or None if the file is not found or an error occurs.
    """
    if not os.path.exists(file_path):
        print(f"Error: IMU data file not found at {file_path}")
        return None

    file_extension = os.path.splitext(file_path)[1].lower()

    if file_extension == '.csv' or file_extension == '.data':
        return read_imu_csv(file_path)
    else:
        print(f"Error: Unsupported IMU data file format: {file_extension}")
        return None

def read_and_merge_imu_data(imu_file_path, mag_file_path):
    """
    Reads and merges IMU (accel/gyro) and magnetometer data.

    Args:
        imu_file_path (str): Path to the IMU data file.
        mag_file_path (str): Path to the magnetometer data file.

    Returns:
        pd.DataFrame: A merged DataFrame with IMU and magnetometer data, or None if reading fails.
    """
    df_imu = read_imu_data(imu_file_path)
    if df_imu is None:
        return None

    if not mag_file_path or not os.path.exists(mag_file_path):
        print("Magnetometer file not provided or not found. Proceeding without magnetometer data.")
        return df_imu

    df_mag = read_imu_data(mag_file_path)
    if df_mag is None:
        return df_imu

    # Rename magnetometer columns to avoid conflicts
    df_mag.rename(columns={'x': 'mag_x', 'y': 'mag_y', 'z': 'mag_z'}, inplace=True)

    # Sort both dataframes by timestamp before merging
    df_imu.sort_values('timestamp', inplace=True)
    df_mag.sort_values('timestamp', inplace=True)

    # Merge dataframes based on the closest timestamp
    merged_df = pd.merge_asof(df_imu, df_mag, on='timestamp', direction='nearest')
    
    print("Successfully merged IMU and magnetometer data.")
    return merged_df


if __name__ == "__main__":
    # Example usage: Create a dummy IMU data file for demonstration
    # In a real scenario, this file would be generated by the sensor.
    dummy_imu_data = {
        'timestamp': [0.0, 0.1, 0.2, 0.3, 0.4],
        'accel_x': [0.1, 0.11, 0.12, 0.13, 0.14],
        'accel_y': [0.0, 0.01, 0.02, 0.03, 0.04],
        'accel_z': [9.8, 9.81, 9.82, 9.83, 9.84],
        'gyro_x': [0.0, 0.001, 0.002, 0.003, 0.004],
        'gyro_y': [0.0, 0.001, 0.002, 0.003, 0.004],
        'gyro_z': [0.0, 0.001, 0.002, 0.003, 0.004],
    }
    dummy_df_imu = pd.DataFrame(dummy_imu_data)
    dummy_imu_file_path = "dummy_imu_data.csv"
    dummy_df_imu.to_csv(dummy_imu_file_path, index=False)
    print(f"Created dummy IMU data file: {dummy_imu_file_path}")

    dummy_mag_data = {
        'timestamp': [0.01, 0.11, 0.21, 0.31, 0.41],
        'x': [20.0, 20.1, 20.2, 20.3, 20.4],
        'y': [5.0, 5.1, 5.2, 5.3, 5.4],
        'z': [40.0, 40.1, 40.2, 40.3, 40.4],
    }
    dummy_df_mag = pd.DataFrame(dummy_mag_data)
    dummy_mag_file_path = "dummy_mag_data.csv"
    dummy_df_mag.to_csv(dummy_mag_file_path, index=False)
    print(f"Created dummy magnetometer data file: {dummy_mag_file_path}")

    # Test reading and merging
    merged_data = read_and_merge_imu_data(dummy_imu_file_path, dummy_mag_file_path)
    if merged_data is not None:
        print("\nMerged IMU and magnetometer data read successfully:")
        print(merged_data.head())
    
    # Clean up dummy files
    os.remove(dummy_imu_file_path)
    os.remove(dummy_mag_file_path)
    print(f"Removed dummy data files.")